DO $$
    DECLARE 
	AGE INT:=18;
	BEGIN
	IF AGE>=18 THEN 
	RAISE NOTICE 'YOUR AGE IS % AND YOU ARE ELIGIBLE TO VOTE',AGE;
	END IF;
	RAISE NOTICE 'YOU ARE INSIDE BEGIN END BLOCK';
	END;
$$
DO $$
    DECLARE 
	AGE INT:=17;
	BEGIN
	IF AGE>=18 THEN 
	RAISE NOTICE 'YOUR AGE IS % AND YOU ARE ELIGIBLE TO VOTE',AGE;
	ELSE 
	RAISE NOTICE 'YOUR AGE IS % AND YOU ARE NOT ELOGIBLE TO VOTE',AGE;
	END IF;
	RAISE NOTICE 'YOU ARE INSIDE BEGIN END BLOCK';
	END;
$$
DO $$
    DECLARE
	SAL INT:=50000;
	SIGN CHAR:='%';
	BEGIN
	IF SAL>10000 AND SAL <20000 THEN
	RAISE NOTICE 'YOUR SALARY IS % AND YOU WILL GET 10% BONUS',SAL,SIGN;
	ELSIF SAL>20000 AND SAL<30000 THEN 
	RAISE NOTICE 'YOUR SALARY IS % AND YOU WILL GET 5% BONUS',SAL,SIGN;
	ELSE 
	RAISE NOTICE 'YOUR SALARY IS % AND YOU WILL GET 2% BONUS',SAL,SIGN;
	END IF;
	RAISE NOTICE 'YOU ARE INSIDE BEGIN END BLOCK';
	END;
$$
