DECLARE
   CURSOR EMP_CURSOR IS SELECT EMP_ID,EMP_SALARY FROM EMPLOYEES;
   V_EMP_ID EMPLOYEES.EMP_ID%TYPE;
   V_EMP_SALARY EMPLOYEES.EMP_NAME%TYPE;
   SALARY_ZERO EXCEPTION;

   BEGIN
    OPEN EMP_CURSOR;
    FETCH EMP_CURSOR INTO V_EMP_ID,V_EMP_SALARY;
    WHILE EMP_CURSOR%FOUND 
    LOOP
        IF V_EMP_SALARY=0 THEN 
        RAISE SALARY_ZERO;
        END IF;

        UPDATE EMPLOYEES
        SET EMP_SALARY=V_EMP_SALARY*0.50
        WHERE EMP_ID=V_EMP_ID;

        FETCH EMP_CURSOR INTO V_EMP_ID,V_EMP_SALARY;
    END LOOP;
    CLOSE EMP_CURSOR;
    EXCEPTION
    WHEN SALARY_ZERO THEN 
     DBMS_OUTPUT.PUT_LINE('SALARY IS ZERO');
   END;
SELECT * FROM EMPLOYEES;
